// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	models "github.com/ugent-library/projects/models"
)

type Project struct {
	Pid                int64
	PrimaryIdentifier  string
	Identifiers        models.Identifiers
	Name               models.TranslatedString
	Description        models.TranslatedString
	FoundingDate       pgtype.Text
	DissolutionDate    pgtype.Text
	Acronym            models.Acronym
	EuGrantCall        pgtype.Text
	EuFundingProgramme pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Ts                 interface{}
}
