CREATE EXTENSION IF NOT EXISTS "unaccent";
DO $$BEGIN CREATE TEXT SEARCH CONFIGURATION "usimple" (COPY = simple);
EXCEPTION
WHEN unique_violation THEN NULL;
END;
$$;

ALTER TEXT SEARCH CONFIGURATION "usimple" ALTER MAPPING FOR hword,
hword_part,
word WITH "unaccent",
simple;

CREATE TABLE IF NOT EXISTS "projects" (
    "pid" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "primary_identifier" character varying NOT NULL,
    "identifiers" jsonb NOT NULL,
    "name" jsonb NOT NULL,
    "description" jsonb NULL,
    "founding_date" character varying NULL,
    "dissolution_date" character varying NULL,
    "acronym" character varying NULL,
    "eu_acronym" character varying NULL,
    "eu_grant" character varying NULL,
    "eu_funding_programme" character varying NULL,
    "created_at" timestamptz NOT NULL,
    "updated_at" timestamptz NOT NULL,
    "ts" tsvector NULL GENERATED ALWAYS AS (
        (
            to_tsvector(
                'simple'::regconfig,
                jsonb_path_query_array(identifier, '$.**{2}'::jsonpath)
            ) || to_tsvector('simple'::regconfig, (id)::text)
        ) || to_tsvector(
            'usimple'::regconfig,
            jsonb_path_query_array(name, '$.**{2}'::jsonpath)
        )
    ) STORED,
    PRIMARY KEY ("pid"),
    UNIQUE ("primary_identifier")
);

CREATE INDEX IF NOT EXISTS "project_ts_idx" ON "projects" USING gin ("ts");

