// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddProject implements addProject operation.
	//
	// Upsert a project.
	//
	// POST /add-project
	AddProject(ctx context.Context, req *Project) error
	// GetProject implements getProject operation.
	//
	// Get a project.
	//
	// POST /get-project
	GetProject(ctx context.Context, req *Identifier) (GetProjectRes, error)
	// SearchProjects implements searchProjects operation.
	//
	// Search projects.
	//
	// POST /search-projects
	SearchProjects(ctx context.Context, req *SearchProjectsRequest) (*ProjectHits, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
