// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// AddProjectOK is response for AddProject operation.
type AddProjectOK struct{}

// Ref: #/components/schemas/AddProjectRequest
type AddProjectRequest struct {
	Type            string                            `json:"type"`
	Identifier      []AddProjectRequestIdentifierItem `json:"identifier"`
	Name            string                            `json:"name"`
	Description     string                            `json:"description"`
	FoundingDate    string                            `json:"foundingDate"`
	DissolutionDate string                            `json:"dissolutionDate"`
}

// GetType returns the value of Type.
func (s *AddProjectRequest) GetType() string {
	return s.Type
}

// GetIdentifier returns the value of Identifier.
func (s *AddProjectRequest) GetIdentifier() []AddProjectRequestIdentifierItem {
	return s.Identifier
}

// GetName returns the value of Name.
func (s *AddProjectRequest) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *AddProjectRequest) GetDescription() string {
	return s.Description
}

// GetFoundingDate returns the value of FoundingDate.
func (s *AddProjectRequest) GetFoundingDate() string {
	return s.FoundingDate
}

// GetDissolutionDate returns the value of DissolutionDate.
func (s *AddProjectRequest) GetDissolutionDate() string {
	return s.DissolutionDate
}

// SetType sets the value of Type.
func (s *AddProjectRequest) SetType(val string) {
	s.Type = val
}

// SetIdentifier sets the value of Identifier.
func (s *AddProjectRequest) SetIdentifier(val []AddProjectRequestIdentifierItem) {
	s.Identifier = val
}

// SetName sets the value of Name.
func (s *AddProjectRequest) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *AddProjectRequest) SetDescription(val string) {
	s.Description = val
}

// SetFoundingDate sets the value of FoundingDate.
func (s *AddProjectRequest) SetFoundingDate(val string) {
	s.FoundingDate = val
}

// SetDissolutionDate sets the value of DissolutionDate.
func (s *AddProjectRequest) SetDissolutionDate(val string) {
	s.DissolutionDate = val
}

type AddProjectRequestIdentifierItem struct {
	Type       string `json:"type"`
	PropertyID string `json:"propertyID"`
	Value      string `json:"value"`
}

// GetType returns the value of Type.
func (s *AddProjectRequestIdentifierItem) GetType() string {
	return s.Type
}

// GetPropertyID returns the value of PropertyID.
func (s *AddProjectRequestIdentifierItem) GetPropertyID() string {
	return s.PropertyID
}

// GetValue returns the value of Value.
func (s *AddProjectRequestIdentifierItem) GetValue() string {
	return s.Value
}

// SetType sets the value of Type.
func (s *AddProjectRequestIdentifierItem) SetType(val string) {
	s.Type = val
}

// SetPropertyID sets the value of PropertyID.
func (s *AddProjectRequestIdentifierItem) SetPropertyID(val string) {
	s.PropertyID = val
}

// SetValue sets the value of Value.
func (s *AddProjectRequestIdentifierItem) SetValue(val string) {
	s.Value = val
}

type ApiKey struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKey) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKey) SetAPIKey(val string) {
	s.APIKey = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/GetProjectRequest
type GetProjectRequest struct {
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *GetProjectRequest) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *GetProjectRequest) SetID(val string) {
	s.ID = val
}

// Ref: #/components/schemas/GetProjectResponse
type GetProjectResponse struct {
	ID              OptString                          `json:"id"`
	Type            string                             `json:"type"`
	Identifier      []GetProjectResponseIdentifierItem `json:"identifier"`
	Name            string                             `json:"name"`
	Description     string                             `json:"description"`
	FoundingDate    string                             `json:"foundingDate"`
	DissolutionDate string                             `json:"dissolutionDate"`
	Created         time.Time                          `json:"created"`
	Modified        time.Time                          `json:"modified"`
}

// GetID returns the value of ID.
func (s *GetProjectResponse) GetID() OptString {
	return s.ID
}

// GetType returns the value of Type.
func (s *GetProjectResponse) GetType() string {
	return s.Type
}

// GetIdentifier returns the value of Identifier.
func (s *GetProjectResponse) GetIdentifier() []GetProjectResponseIdentifierItem {
	return s.Identifier
}

// GetName returns the value of Name.
func (s *GetProjectResponse) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *GetProjectResponse) GetDescription() string {
	return s.Description
}

// GetFoundingDate returns the value of FoundingDate.
func (s *GetProjectResponse) GetFoundingDate() string {
	return s.FoundingDate
}

// GetDissolutionDate returns the value of DissolutionDate.
func (s *GetProjectResponse) GetDissolutionDate() string {
	return s.DissolutionDate
}

// GetCreated returns the value of Created.
func (s *GetProjectResponse) GetCreated() time.Time {
	return s.Created
}

// GetModified returns the value of Modified.
func (s *GetProjectResponse) GetModified() time.Time {
	return s.Modified
}

// SetID sets the value of ID.
func (s *GetProjectResponse) SetID(val OptString) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *GetProjectResponse) SetType(val string) {
	s.Type = val
}

// SetIdentifier sets the value of Identifier.
func (s *GetProjectResponse) SetIdentifier(val []GetProjectResponseIdentifierItem) {
	s.Identifier = val
}

// SetName sets the value of Name.
func (s *GetProjectResponse) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *GetProjectResponse) SetDescription(val string) {
	s.Description = val
}

// SetFoundingDate sets the value of FoundingDate.
func (s *GetProjectResponse) SetFoundingDate(val string) {
	s.FoundingDate = val
}

// SetDissolutionDate sets the value of DissolutionDate.
func (s *GetProjectResponse) SetDissolutionDate(val string) {
	s.DissolutionDate = val
}

// SetCreated sets the value of Created.
func (s *GetProjectResponse) SetCreated(val time.Time) {
	s.Created = val
}

// SetModified sets the value of Modified.
func (s *GetProjectResponse) SetModified(val time.Time) {
	s.Modified = val
}

type GetProjectResponseIdentifierItem struct {
	Type       string `json:"type"`
	PropertyID string `json:"propertyID"`
	Value      string `json:"value"`
}

// GetType returns the value of Type.
func (s *GetProjectResponseIdentifierItem) GetType() string {
	return s.Type
}

// GetPropertyID returns the value of PropertyID.
func (s *GetProjectResponseIdentifierItem) GetPropertyID() string {
	return s.PropertyID
}

// GetValue returns the value of Value.
func (s *GetProjectResponseIdentifierItem) GetValue() string {
	return s.Value
}

// SetType sets the value of Type.
func (s *GetProjectResponseIdentifierItem) SetType(val string) {
	s.Type = val
}

// SetPropertyID sets the value of PropertyID.
func (s *GetProjectResponseIdentifierItem) SetPropertyID(val string) {
	s.PropertyID = val
}

// SetValue sets the value of Value.
func (s *GetProjectResponseIdentifierItem) SetValue(val string) {
	s.Value = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
