// Code generated by ogen, DO NOT EDIT.
package api

type AddProjectRes interface {
	addProjectRes()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type GetProjectRes interface {
	getProjectRes()
}
