// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddProject implements addProject operation.
//
// Add a single project.
//
// POST /add-project
func (UnimplementedHandler) AddProject(ctx context.Context, req *AddProject) (r AddProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProject implements deleteProject operation.
//
// Delete a record.
//
// POST /delete-record
func (UnimplementedHandler) DeleteProject(ctx context.Context, req *DeleteProjectRequest) (r DeleteProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements getProject operation.
//
// Get a project.
//
// POST /get-project
func (UnimplementedHandler) GetProject(ctx context.Context, req *GetProjectRequest) (r GetProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SuggestProjects implements suggestProjects operation.
//
// Search in projects.
//
// POST /suggest-projects
func (UnimplementedHandler) SuggestProjects(ctx context.Context, req *SuggestProjectsRequest) (r *SuggestProjectsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
