// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "identifier", Type: field.TypeJSON},
		{Name: "name", Type: field.TypeJSON},
		{Name: "description", Type: field.TypeJSON},
		{Name: "founding_date", Type: field.TypeString, Nullable: true},
		{Name: "dissolution_date", Type: field.TypeString, Nullable: true},
		{Name: "acronym", Type: field.TypeString, Nullable: true},
		{Name: "grant_id", Type: field.TypeString, Nullable: true},
		{Name: "funding_programme", Type: field.TypeString, Nullable: true},
		{Name: "deleted", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_identifier_id", Type: field.TypeInt},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "projects_project_identifiers_projects",
				Columns:    []*schema.Column{ProjectsColumns[12]},
				RefColumns: []*schema.Column{ProjectIdentifiersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "project_project_identifier_id",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[12]},
			},
		},
	}
	// ProjectIdentifiersColumns holds the columns for the "project_identifiers" table.
	ProjectIdentifiersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "external_id", Type: field.TypeString, Unique: true},
	}
	// ProjectIdentifiersTable holds the schema information for the "project_identifiers" table.
	ProjectIdentifiersTable = &schema.Table{
		Name:       "project_identifiers",
		Columns:    ProjectIdentifiersColumns,
		PrimaryKey: []*schema.Column{ProjectIdentifiersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectsTable,
		ProjectIdentifiersTable,
	}
)

func init() {
	ProjectsTable.ForeignKeys[0].RefTable = ProjectIdentifiersTable
}
