// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ugent-library/projects/ent/predicate"
	"github.com/ugent-library/projects/ent/project"
	"github.com/ugent-library/projects/ent/projectidentifier"
)

// ProjectIdentifierQuery is the builder for querying ProjectIdentifier entities.
type ProjectIdentifierQuery struct {
	config
	ctx          *QueryContext
	order        []projectidentifier.OrderOption
	inters       []Interceptor
	predicates   []predicate.ProjectIdentifier
	withProjects *ProjectQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectIdentifierQuery builder.
func (piq *ProjectIdentifierQuery) Where(ps ...predicate.ProjectIdentifier) *ProjectIdentifierQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *ProjectIdentifierQuery) Limit(limit int) *ProjectIdentifierQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *ProjectIdentifierQuery) Offset(offset int) *ProjectIdentifierQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *ProjectIdentifierQuery) Unique(unique bool) *ProjectIdentifierQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *ProjectIdentifierQuery) Order(o ...projectidentifier.OrderOption) *ProjectIdentifierQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryProjects chains the current query on the "projects" edge.
func (piq *ProjectIdentifierQuery) QueryProjects() *ProjectQuery {
	query := (&ProjectClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectidentifier.Table, projectidentifier.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, projectidentifier.ProjectsTable, projectidentifier.ProjectsColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProjectIdentifier entity from the query.
// Returns a *NotFoundError when no ProjectIdentifier was found.
func (piq *ProjectIdentifierQuery) First(ctx context.Context) (*ProjectIdentifier, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projectidentifier.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) FirstX(ctx context.Context) *ProjectIdentifier {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectIdentifier ID from the query.
// Returns a *NotFoundError when no ProjectIdentifier ID was found.
func (piq *ProjectIdentifierQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projectidentifier.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) FirstIDX(ctx context.Context) int {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectIdentifier entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectIdentifier entity is found.
// Returns a *NotFoundError when no ProjectIdentifier entities are found.
func (piq *ProjectIdentifierQuery) Only(ctx context.Context) (*ProjectIdentifier, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projectidentifier.Label}
	default:
		return nil, &NotSingularError{projectidentifier.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) OnlyX(ctx context.Context) *ProjectIdentifier {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectIdentifier ID in the query.
// Returns a *NotSingularError when more than one ProjectIdentifier ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *ProjectIdentifierQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projectidentifier.Label}
	default:
		err = &NotSingularError{projectidentifier.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) OnlyIDX(ctx context.Context) int {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectIdentifiers.
func (piq *ProjectIdentifierQuery) All(ctx context.Context) ([]*ProjectIdentifier, error) {
	ctx = setContextOp(ctx, piq.ctx, "All")
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectIdentifier, *ProjectIdentifierQuery]()
	return withInterceptors[[]*ProjectIdentifier](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) AllX(ctx context.Context) []*ProjectIdentifier {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectIdentifier IDs.
func (piq *ProjectIdentifierQuery) IDs(ctx context.Context) (ids []int, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, "IDs")
	if err = piq.Select(projectidentifier.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) IDsX(ctx context.Context) []int {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *ProjectIdentifierQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, "Count")
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*ProjectIdentifierQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *ProjectIdentifierQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, "Exist")
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *ProjectIdentifierQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectIdentifierQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *ProjectIdentifierQuery) Clone() *ProjectIdentifierQuery {
	if piq == nil {
		return nil
	}
	return &ProjectIdentifierQuery{
		config:       piq.config,
		ctx:          piq.ctx.Clone(),
		order:        append([]projectidentifier.OrderOption{}, piq.order...),
		inters:       append([]Interceptor{}, piq.inters...),
		predicates:   append([]predicate.ProjectIdentifier{}, piq.predicates...),
		withProjects: piq.withProjects.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithProjects tells the query-builder to eager-load the nodes that are connected to
// the "projects" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *ProjectIdentifierQuery) WithProjects(opts ...func(*ProjectQuery)) *ProjectIdentifierQuery {
	query := (&ProjectClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withProjects = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ExternalID string `json:"external_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectIdentifier.Query().
//		GroupBy(projectidentifier.FieldExternalID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *ProjectIdentifierQuery) GroupBy(field string, fields ...string) *ProjectIdentifierGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectIdentifierGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = projectidentifier.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ExternalID string `json:"external_id,omitempty"`
//	}
//
//	client.ProjectIdentifier.Query().
//		Select(projectidentifier.FieldExternalID).
//		Scan(ctx, &v)
func (piq *ProjectIdentifierQuery) Select(fields ...string) *ProjectIdentifierSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &ProjectIdentifierSelect{ProjectIdentifierQuery: piq}
	sbuild.label = projectidentifier.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectIdentifierSelect configured with the given aggregations.
func (piq *ProjectIdentifierQuery) Aggregate(fns ...AggregateFunc) *ProjectIdentifierSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *ProjectIdentifierQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !projectidentifier.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *ProjectIdentifierQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectIdentifier, error) {
	var (
		nodes       = []*ProjectIdentifier{}
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withProjects != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectIdentifier).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectIdentifier{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withProjects; query != nil {
		if err := piq.loadProjects(ctx, query, nodes,
			func(n *ProjectIdentifier) { n.Edges.Projects = []*Project{} },
			func(n *ProjectIdentifier, e *Project) { n.Edges.Projects = append(n.Edges.Projects, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *ProjectIdentifierQuery) loadProjects(ctx context.Context, query *ProjectQuery, nodes []*ProjectIdentifier, init func(*ProjectIdentifier), assign func(*ProjectIdentifier, *Project)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProjectIdentifier)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(project.FieldProjectIdentifierID)
	}
	query.Where(predicate.Project(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(projectidentifier.ProjectsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProjectIdentifierID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "project_identifier_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (piq *ProjectIdentifierQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *ProjectIdentifierQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projectidentifier.Table, projectidentifier.Columns, sqlgraph.NewFieldSpec(projectidentifier.FieldID, field.TypeInt))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectidentifier.FieldID)
		for i := range fields {
			if fields[i] != projectidentifier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *ProjectIdentifierQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(projectidentifier.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = projectidentifier.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProjectIdentifierGroupBy is the group-by builder for ProjectIdentifier entities.
type ProjectIdentifierGroupBy struct {
	selector
	build *ProjectIdentifierQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *ProjectIdentifierGroupBy) Aggregate(fns ...AggregateFunc) *ProjectIdentifierGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *ProjectIdentifierGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, "GroupBy")
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectIdentifierQuery, *ProjectIdentifierGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *ProjectIdentifierGroupBy) sqlScan(ctx context.Context, root *ProjectIdentifierQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectIdentifierSelect is the builder for selecting fields of ProjectIdentifier entities.
type ProjectIdentifierSelect struct {
	*ProjectIdentifierQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *ProjectIdentifierSelect) Aggregate(fns ...AggregateFunc) *ProjectIdentifierSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *ProjectIdentifierSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, "Select")
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectIdentifierQuery, *ProjectIdentifierSelect](ctx, pis.ProjectIdentifierQuery, pis, pis.inters, v)
}

func (pis *ProjectIdentifierSelect) sqlScan(ctx context.Context, root *ProjectIdentifierQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
