// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ugent-library/projects/ent/predicate"
	"github.com/ugent-library/projects/ent/projectidentifier"
)

// ProjectIdentifierDelete is the builder for deleting a ProjectIdentifier entity.
type ProjectIdentifierDelete struct {
	config
	hooks    []Hook
	mutation *ProjectIdentifierMutation
}

// Where appends a list predicates to the ProjectIdentifierDelete builder.
func (pid *ProjectIdentifierDelete) Where(ps ...predicate.ProjectIdentifier) *ProjectIdentifierDelete {
	pid.mutation.Where(ps...)
	return pid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pid *ProjectIdentifierDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pid.sqlExec, pid.mutation, pid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pid *ProjectIdentifierDelete) ExecX(ctx context.Context) int {
	n, err := pid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pid *ProjectIdentifierDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(projectidentifier.Table, sqlgraph.NewFieldSpec(projectidentifier.FieldID, field.TypeInt))
	if ps := pid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pid.mutation.done = true
	return affected, err
}

// ProjectIdentifierDeleteOne is the builder for deleting a single ProjectIdentifier entity.
type ProjectIdentifierDeleteOne struct {
	pid *ProjectIdentifierDelete
}

// Where appends a list predicates to the ProjectIdentifierDelete builder.
func (pido *ProjectIdentifierDeleteOne) Where(ps ...predicate.ProjectIdentifier) *ProjectIdentifierDeleteOne {
	pido.pid.mutation.Where(ps...)
	return pido
}

// Exec executes the deletion query.
func (pido *ProjectIdentifierDeleteOne) Exec(ctx context.Context) error {
	n, err := pido.pid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{projectidentifier.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pido *ProjectIdentifierDeleteOne) ExecX(ctx context.Context) {
	if err := pido.Exec(ctx); err != nil {
		panic(err)
	}
}
