// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ugent-library/projects/ent/project"
	"github.com/ugent-library/projects/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescIdentifier is the schema descriptor for identifier field.
	projectDescIdentifier := projectFields[1].Descriptor()
	// project.DefaultIdentifier holds the default value on creation for the identifier field.
	project.DefaultIdentifier = projectDescIdentifier.Default.(schema.Identifier)
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[2].Descriptor()
	// project.DefaultName holds the default value on creation for the name field.
	project.DefaultName = projectDescName.Default.(schema.TranslatedString)
	// projectDescDescription is the schema descriptor for description field.
	projectDescDescription := projectFields[3].Descriptor()
	// project.DefaultDescription holds the default value on creation for the description field.
	project.DefaultDescription = projectDescDescription.Default.(schema.TranslatedString)
	// projectDescDeleted is the schema descriptor for deleted field.
	projectDescDeleted := projectFields[9].Descriptor()
	// project.DefaultDeleted holds the default value on creation for the deleted field.
	project.DefaultDeleted = projectDescDeleted.Default.(bool)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[10].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[11].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
}
